### ISSUE TITLE
Sector Windows are not updating after committing once

### ISSUE THREAD

**Issue by Karjala22** [df21-net/editor#16]
To reproduce. Choose a sector, change a floor altitude value (or any editable field) and **highlight it** . Choose another sector with a different value of the floor altitude. The value displayed in the sector editor is the old one. However, if you click on the sector editor again - the value is updated. I am guessing the issue is due to it not refreshing. 

The interesting thing is if you click on another sector the name of the sector editor window is updated, but no the highlighted fields. 

![image](https://user-images.githubusercontent.com/78927981/121706938-1888d500-caa4-11eb-85c8-70d23d6f9822.png)

The editor click that updates the sector editor window is in **M_EDITOR.PAS** and looks like this

`
procedure DO_Fill_SectorEditor;
var
  TheSector : TSector;
  numvx     : Integer;
  numwl     : Integer;
begin
 TheSector := TSector(MAP_SEC.Objects[SC_HILITE]);
 numvx     := TheSector.Vx.Count;
 numwl     := TheSector.Wl.Count;
 SectorEditor.Caption := Format('SC %d  %s', [SC_HILITE, TheSector.Name]);
 SectorEditor.SCEd.Cells[1,  0] := TheSector.Name;
 SectorEditor.SCEd.Cells[1,  1] := IntToStr(TheSector.Ambient);
 SectorEditor.SCEd.Cells[1,  2] := IntToStr(TheSector.Flag1);
 SectorEditor.SCEd.Cells[1,  3] := IntToStr(TheSector.Flag2);
 SectorEditor.SCEd.Cells[1,  4] := IntToStr(TheSector.Flag3);
 SectorEditor.SCEd.Cells[1,  5] := RTrim(Format('%-5.2f', [TheSector.Floor_Alt]));
 SectorEditor.SCEd.Cells[1,  6] := TheSector.Floor.Name;
 SectorEditor.SCEd.Cells[1,  7] := RTrim(Format('%-5.2f', [TheSector.Floor.f1]));
 SectorEditor.SCEd.Cells[1,  8] := RTrim(Format('%-5.2f', [TheSector.Floor.f2]));
 SectorEditor.SCEd.Cells[1,  9] := IntToStr(TheSector.Floor.i);
 SectorEditor.SCEd.Cells[1, 10] := RTrim(Format('%-5.2f', [TheSector.Ceili_Alt]));
 SectorEditor.SCEd.Cells[1, 11] := TheSector.Ceili.Name;
 SectorEditor.SCEd.Cells[1, 12] := RTrim(Format('%-5.2f', [TheSector.Ceili.f1]));
 SectorEditor.SCEd.Cells[1, 13] := RTrim(Format('%-5.2f', [TheSector.Ceili.f2]));
 SectorEditor.SCEd.Cells[1, 14] := IntToStr(TheSector.Ceili.i);
 SectorEditor.SCEd.Cells[1, 15] := RTrim(Format('%-5.2f', [TheSector.Second_Alt]));
 SectorEditor.SCEd.Cells[1, 16] := IntToStr(TheSector.Layer);

 SectorEditor.PanelVXNum.Caption := IntToStr(numvx);
 SectorEditor.PanelWLNum.Caption := IntToStr(numwl);

 DO_SectorEditor_Specials_Init;
`

The Actual window is defined in **M_SCEDIT.PAS**

**Comment by azurda** [comment]
Fixed in https://github.com/df21-net/editor/pull/23
